### ISSUE TITLE
Hello, could you please tell me how I can run the Fun Model with Tora?

### ISSUE THREAD

**Issue by leetraman822** [kijai/ComfyUI-CogVideoXWrapper#198]
I noticed that the latest update supports the Tora model, but I can't figure out how to make it work.

**Comment by 4lt3r3go** [comment]
i don't understand either the Tora Xfun support.
TORA doesnt work with Xfun models, only 5B_I2V. 
Maybe i'm missing a TORA XFUN model released somewere that i'm not aware about.
sooo much confusion with all this Cogs 😂

**Comment by kijai** [comment]
It does work, it's just clumsy to use because the Fun sampler resizes the input to the closest bucket resolution (which is something I want to get rid of, but that's more work to do properly than I have time currently), you can see what that is in the log, and also with this node:

![image](https://github.com/user-attachments/assets/64e5474b-bb1b-4b0e-92c1-7b7a28d303e8)

All the resolutions and frame counts need to match for it to work.

https://github.com/user-attachments/assets/0d7c5fda-7874-4353-9fc7-b04dbdf2e713

It can even be used with vid2vid as extra guidance:

https://github.com/user-attachments/assets/4d91fa41-0f33-45fd-a19a-da017b7215dd

**Comment by 4lt3r3go** [comment]
```
Error while processing rearrange-reduction pattern "B (T H W) C -> (B T) C H W".
Input tensor shape: torch.Size([2, 3724, 3072]). Additional info: {'H': 52, 'W': 78}.
Shape mismatch, can't divide axis of length 3724 in chunks of 4056
```

spent half day, i'm unable to make it work even with the "closest bucket" node.
i'm using    alibaba-pai cogvideoXfun 1.1 5b Inp  , 
trying ake this work in image to video

**Comment by kijai** [comment]
> 
> 
> spent half day, i'm unable to make it work even with the "closest bucket" node.
> 
> got this:
> ```
> Error while processing rearrange-reduction pattern "B (T H W) C -> (B T) C H W".
> Input tensor shape: torch.Size([2, 3724, 3072]). Additional info: {'H': 52, 'W': 78}.
> Shape mismatch, can't divide axis of length 3724 in chunks of 4056
> ```
> 
> 
> i'm using    alibaba-pai cogvideoXfun 1.1 5b Inp  , 
> trying ake this work in image to video
> 

Some dimension do not match, try with a simple 512x512 input because that will not get resized. The spline editor has to be set to same size, along with everything else.

**Comment by 4lt3r3go** [comment]
thanks for your time and your incredible work on all this.
I got it to work finally. 
Sadly there's no 2B tora version .. my 3090 is suffering with 5B😁

anyway, already got few really nice results, gonna show some on reddit. People need to know!

**Comment by 4lt3r3go** [comment]
any plans on 2B tora?
also is there a way to add more splines to move different objects in different direction? 
i saw some examples of tora around doing that,   can't find a way to do this

**Comment by kijai** [comment]
> thanks for your time and your incredible work on all this. I got it to work finally. any plans on 2B tora? also, is there a way to add more splines to move different objects in different direction? i saw some examples of tora around doing that, can't find a way to do this

It doesn't seem to work with the 2b models because the embed sizes don't match, I don't know if it can work, probably not.

For multiple trajectories you can use multiple spline editors and join the coordinates with this (node is in KJNodes):

![image](https://github.com/user-attachments/assets/a802f8a4-6ea5-477e-a002-b5a497404f3f)

**Comment by Ratinod** [comment]
> It doesn't seem to work with the 2b models because the embed sizes don't match, I don't know if it can work, probably not.

It's very sad... I really wanted it to work together with the "NimVideo/cogvideox-2b-img2vid" model, because in my opinion this is the best ratio of speed and quality for local i2v generation right now. And "Tora" would make it even better.

**Comment by 4lt3r3go** [comment]
> > It doesn't seem to work with the 2b models because the embed sizes don't match, I don't know if it can work, probably not.
> 
> It's very sad... I really wanted it to work together with the "NimVideo/cogvideox-2b-img2vid" model, because in my opinion this is the best ratio of speed, quality and low VRAM consumption for local i2v generation right now. And "Tora" would make it even better.


i'm honestly way more interested in making this works with xfun 2b model out than that NimVideo, wich is an incredible model don't get me wrong... but the ability to pick a "start" and "end" image in Xfun provide way more possibilities.
[this workflow here](https://civitai.com/models/866210/its-alive-fast-i2v-or-firstlast-frame-or-cogvideo-x-fun11-2b5b-or-comfy-custom-workflow?modelVersionId=986816 ) for example use Xfun i2v and i love it.

**Comment by kijai** [comment]
It's just not going to work with 2b, it would require training new Tora model for 2b.

The GGUF version of 5b doesn't use that much memory and it can work with really small resolutions, smaller than what 2b can do. At 512x512 the 5b model with Tora fits under 12GB.

**Comment by 4lt3r3go** [comment]
> It's just not going to work with 2b, it would require training new Tora model for 2b.
> 
> The GGUF version of 5b doesn't use that much memory and it can work with really small resolutions, smaller than what 2b can do. At 512x512 the 5b model with Tora fits under 12GB.

It’s not a matter of memory🙂 (i'm on 3090) it’s that the new 2B model has been released and claims to be as good as version 5B while also being much faster.. is not really like that in my opinion but is really impressive what 2B can do now.
Additionally, there are some workflows for creating animations that are based on the FunX 2B as a strength for speed. 
Despite being less accurate, 2b’s high speed often makes it very useful for some tasks.
Personally, if I had a Tora that works with 2B, I’d probably be the happiest person in the world.
A bunch of nvidia H100 would help the happiness too 😁

**Comment by kijai** [comment]
> > It's just not going to work with 2b, it would require training new Tora model for 2b.
> > The GGUF version of 5b doesn't use that much memory and it can work with really small resolutions, smaller than what 2b can do. At 512x512 the 5b model with Tora fits under 12GB.
> 
> It’s not a matter of memory🙂 (i'm on 3090) it’s that the new 2B model has been released and claims to be as good as version 5B while also being much faster.. is not really like that in my opinion but is really impressive what 2B can do now. Additionally, there are some workflows for creating animations that are based on the FunX 2B as a strength for speed. Despite being less accurate, 2b’s high speed often makes it very useful for some tasks. Personally, if I had a Tora that works with 2B, I’d probably be the happiest person in the world. A bunch of nvidia H100 would help the happiness too 😁

In my experience the 5B I2V is still lot better quality. Also the Fun- models are more interesting because the resolution and frame count is not locked like the I2V models are.

Anyway it's just not going to work without re-training, nothing I can do about Tora + 2B.

**Comment by 4lt3r3go** [comment]
yes agree as i sayd already, 5B is superior🙂
but If only God existed, he’d probably know how many tests I’ve done on both models. 
I can assure you there are plenty of useful applications for the 2B models specifically because of their speed. 
I can only hope they release TORA 2b at some point. 
It’s always good to have more options when it comes to creating videos, where every second saved is welcome, 
and having more choices is always better.
I know it’s hard with all the amazing work you’re doing, but whenever you have a couple of minutes, I recommend trying out this workflow. [https://civitai.com/models/866210?modelVersionId=1020506]

**Comment by 4lt3r3go** [comment]
yes agree 100%, 5B is superior, no doubts 🙂
but If only God existed, he’d probably know how many tests I’ve done on both models. 
I've found plenty of useful applications for the 2B models specifically because of their speed so let's hope they release TORA 2b at some point. 

I know it’s hard with all the amazing work you’re doing, 
but whenever you have a couple of minutes, I’d love to hear your opinion on this workflow, 
but maybe that’s asking too much😁 https://civitai.com/models/866210?modelVersionId=1020506
