### ISSUE TITLE
Question on Quantized version

### ISSUE THREAD

**Issue by azoksky** [kijai/ComfyUI-CogVideoXWrapper#28]
Hi, this is wonderful job to bring it to comfyui. However, with limited resouces I am unable to run 5b version. Since the model has transformer architecture, can't we quantize it to make it fit in low-end systems with 6gb cards? Since gguf formats are omnipreset and users are much more comfortable using it, I guess that is the way forward.

**Comment by kijai** [comment]
Maybe, I'm unsure how it would perform at 4bit, it's already possible to do fp8 with these nodes. I also added the diffusers `sequential_cpu_offload` as option, it will reduce the VRAM use a lot (16 frames would be only about 3GB), but also slow down the process.

**Comment by azoksky** [comment]
The thing is it has only 12 gb RAM and 15 gb vram and I am already using ggfu q4 version of T5 text encoder. Unfortunately it loads the cogx5b in the ram and crashes.  However, I am able to run 2b version smoothly. Will try sequential_cpu_offload node to see if something happens positively. Also fp8 option is not supported by the  t4 GPU. If possible, can u upload a quantized 8 or 6 bit version of the cogxvideo-5b , or help me with any conversion tips. Any help is appreciated. Selfless people like you who spend countless hours to mAke this community stronger everyday are really inspirational.  Thank u.

**Comment by GiusTex** [comment]
> Unfortunately it loads the cogx5b in the ram and crashes.

I had a similar problem: everything loaded but then the script got stuck at 0% 

<details>
<summary>Details</summary>

(I have windows 11, nvidia rtx 3060 12 gb vram, 64 gb ram; I haven't tried today the `fp8 transformer` option but yesterday it didn't work: `Unsupported type of tensor: nullptr (uninitialized)`, and yesterday there wasn't the `cpu offload` option and I deleted the full model in the meantime)

</details>

, anyway if you want to test the model while waiting for the gguf version you can use [camenduru's 8bit version](https://huggingface.co/camenduru/CogVideoX-5b-8bit/tree/main/transformer), it worked for me, I downloaded and renamed the model into `diffusion_pytorch_model.safetensors`, and changed the existing `diffusion_pytorch_model.index.safetensors` with the camenduru's `config.json`. Sadly the fp8 model too didn't fit for an inch in my vram (around 12,8 vram against a total of 12), so I had to turn on the `cpu offload` option and with that the fp8 version worked using only 2gb vram, such a waste of my rtx; 

<details>
<summary>Thoughts</summary>

I suppose that since I'm using the cpu option maybe we could even have enough vram left for the full model, but I'll make the vram usage and speed comparison test when I'll have the will to download it again

</details>

**Comment by kijai** [comment]
`Unsupported type of tensor: nullptr (uninitialized)`
I have never seen this before, what torch version are you using?

**Comment by GiusTex** [comment]
Me neither, it was a rare bug also to find online, only around 2-3 cases
````
open-clip-torch           2.24.0                   
pytorch                   2.1.2           
pytorch-cuda              12.1                
pytorch-lightning         2.2.5                    
pytorch-mutex             1.0                        
torch                     2.3.1+cu121             
torchaudio                2.3.1+cu121             
torchmetrics              1.4.0.post0             
torchsde                  0.2.6                   
torchvision               0.16.2
diffusers                 0.30.1
```

**Comment by patientx** [comment]
> > Unfortunately it loads the cogx5b in the ram and crashes.
> 
> I had a similar problem: everything loaded but then the script got stuck at 0%
> 
> Details
> , anyway if you want to test the model while waiting for the gguf version you can use [camenduru's 8bit version](https://huggingface.co/camenduru/CogVideoX-5b-8bit/tree/main/transformer), it worked for me, I downloaded and renamed the model into `diffusion_pytorch_model.safetensors`, and changed the existing `diffusion_pytorch_model.index.safetensors` with the camenduru's `config.json`. Sadly the fp8 model too didn't fit for an inch in my vram (around 12,8 vram against a total of 12), so I had to turn on the `cpu offload` option and with that the fp8 version worked using only around 3gb vram, such a waste of my rtx;
> 
> Thoughts
> #### Edit:
> Ah and I too am using the t5-v1_1-xxl-Q8.gguf, which is half the size of the full clip

can you share your workflow please ?

**Comment by GiusTex** [comment]
Sure: [CogVideoX-5b_workflow.json](https://github.com/user-attachments/files/16803274/CogVideoX-5b_workflow.json)
Also, at the moment in the transformer folder there is the fp8 version

![Screen](https://github.com/user-attachments/assets/bdc10aeb-44cc-442a-a160-317915653e8a)

When I want to use the full model I rename the folder into smth else, like `transformer_fp8`, and rename `transformer_full` into `transformer`, this way you have both models and you are telling the script which folder to see. You can make a test to see what's best for you and then delete what necessary.

![image](https://github.com/user-attachments/assets/90c6ad22-88e0-4549-8c86-f2e837ff7e38)

In the full model folder I have this:

![Screen1](https://github.com/user-attachments/assets/0478eba2-4d36-4927-90fd-c40080174c37)

**Comment by patientx** [comment]
> Sure: [CogVideoX-5b_workflow.json](https://github.com/user-attachments/files/16803274/CogVideoX-5b_workflow.json) 

Thanks, just downloaded vae and other smallers files (not transformers or t5 clips) and made the rest of the folders then put the smaller model with config inside, It worked BUT as usual with my gpu it gave up on vae decoding. In the past with other video models I needed some tricks , also if we can use our own vae tiling maybe I could get around this. (amd rx 6600 with zluda) , at cfg 1 it takes around 30-35 sec per iteration (just to test stuff , I wasn't going to wait forever for potentially getting errors in the end and I was right:) )

**Comment by GiusTex** [comment]
> it gave up on vae decoding.

Same here... I'm testing the cogvideo decode node options to see if someone can make it work 'till the end
