### ISSUE TITLE
weird issue after lates update?

### ISSUE THREAD

**Issue by 4lt3r3go** [kijai/ComfyUI-CogVideoXWrapper#283]
I don’t know how else to explain it other than showing it in a video.
Before this latest update, I could easily use InP with "Start and End images," but now it seems to cause issues. Toward the end, the video tends to shift to gray/noise.
I’ve tried various samplers and tweaking the "noise aug settings," but nothing works.
This didn’t happen before. The issue disappears if you use just a single frame (without an end frame).

I frequently use the "Fun-InP" models, which, despite being labeled as in-paint (still a mystery how to use them as in-paint, but OK), were the only COG models that allowed to achieve specific results in short time.

Has something changed with this latest update?

**Comment by 4lt3r3go** [comment]
https://github.com/user-attachments/assets/ed3c8838-ce08-4316-a0f6-6115e165ce38

**Comment by 4lt3r3go** [comment]
the problem seems more obvious on 2b InP (video above)
but happen also with latest 5B 1.5 I2V when using the proper ImageEncode for each

**Comment by kijai** [comment]
Are you using the FunInP version of the image encode? It was the only node that I still had to do different for the inpainting models. They are called inpainting because the frames that are diffused, as in everything but start/end are masked. I'm unsure if the masking/inpainting can be otherwise utilized, it's on my list of things to get into.

![image](https://github.com/user-attachments/assets/abfe3baa-6775-43ed-ab65-42e518f31561)

**Comment by kijai** [comment]
Okay nevermind, I think I have replicated the issue, the last latent is somehow wrong.

**Comment by kijai** [comment]
Right, so turns out the end image latent should not be masked, removing that seems to have fixed the last latent going to noise with the InP models.

**Comment by 4lt3r3go** [comment]
**GREAT!!! 🖤**now works like before!

- about interpolation:
I've tested all the models really extensively, and the interpolation model didn't give me good results. Instead, the inP model seems to work better at that interpolation task.
I'll give the interpolation model another chance.

- about start/end frames:
I've been struggling for days trying to figure out the most appropriate way to offer a workflow that allows selecting start and end frames via a selector. The problem is that all the image switches I've tried require actually images as input. 
However, in cases where the end frame needs to be left empty (allowing the model to freely create an ending) the selector freezes because it doesn’t receive any frame on the other side of the cable. 
Do you have any idea how to workaround on this? 
I’ve tried opening an issue on the impact pack, but they haven’t responded.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/825

**Comment by Harry-Monk** [comment]
I'm still having trouble with the CogVideo ImageEncode FunInP node since Update8 unfortunately (up-to-date at time of posting).

I'm still getting the 'fade-to-grey' issue when using the 'CogVideoX_5b_fun_1_1_GGUF_Q4_0.safetensors' model. Is the GGUF one even supposed to be able to do I2V / Interpolation (I could have sworn it used to, before Update8)?

Steps to reproduce:
1. Load the 'cogvideox_Fun_I2V_02.json' example.
2. Change the loader node to '(Down)load CogVideo GGUF Model' and select 'CogVideoX_5b_fun_1_1_GGUF_Q4_0.safetensors'.
3. Load the fireworks image.

Result (looks more like a 'fade-from-grey' issue in this case, rather than 'fade-to-grey':

https://github.com/user-attachments/assets/8d9b4e19-fa15-4165-9c12-d4312d2be7fa

I noticed that with the GGUF model, the log is missing the 'More than one image conditioning received, interpolating' entry, so I'm assuming something's not quite right somewhere:

![image](https://github.com/user-attachments/assets/cc118e29-064b-45d1-9e9d-d2f1df0d7878)

But I even get the same issue with the default model 'alibaba-pai/CogVideoX-Fun-V1.1-5b-Inp':

https://github.com/user-attachments/assets/7f72a932-a964-4f8f-8c16-0e01b8c71d27

Although when using that one, at least the log does show the interpolation confirmation message:

![image](https://github.com/user-attachments/assets/5dabbfee-50bb-407b-bacb-830083ed32d7)

As mentioned above, the 'CogVideoX_5b_Intepolation_GGUF_Q4_0.safetensors' model works perfectly, for both I2V and Interpolation, but I'd still prefer to use the Fun model if possible, as it frees up a bit more VRAM for other things.

Note: I'm on a 2080Ti, if that makes any difference?

**Comment by 4lt3r3go** [comment]
"17 instead of 16 and 9 instead of 8"
🤔
i remember that i setted a slider to match certain steps and now all seems to be changed.
2b likes 17 frames
5b don't, 16 frames works.

good to discover here randomly that at least now the module wont stuck anymore if frames amount is not correct, something was happening before.

now i need to understand again wich frames amount range are accepted by all this models 😁

**Comment by 4lt3r3go** [comment]
no never mind. my bad. i'm just confused.

**Comment by PeterTucker** [comment]
@Harry-Monk , I'm stills struggling with this grey-render issue. Any way you could post your workflow?

Did you get it working with CogVideoX_5b_fun_1_1_GGUF_Q4_0.safetensors?

**Comment by PeterTucker** [comment]
@kijai, so I was able to get this running. Is there any chance we could get a 2b GGUF version?
